services:
  - type: web
    name: cardify
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: STRIPE_SECRET_KEY
        sync: false
